[package]
name = "cow_bot"
version = "0.1.0"
edition = "2021"

[dependencies]
serenity = "0.12.2"
tokio = { version = "1.41.0", features = ["full" ] }
env_logger = "0.11.5"
poise = { git = "https://github.com/serenity-rs/poise", branch = "current" }
serde = { version = "1.0", features = ["derive"] }
reqwest = { version = "0.12.9", features = ["json"] }
serde_json = "1.0.132"

[build-dependencies]
cc = "1.1.31"
