[package]
name = "cow_bot"
version = "0.1.0"
edition = "2021"

[dependencies]
serenity = "0.12.4"
tokio = { version = "1.42.0", features = ["full"] }
env_logger = "0.11.5"
poise = { git = "https://github.com/serenity-rs/poise", branch = "current" }
serde = { version = "1.0.216", features = ["derive"] }
reqwest = { version = "0.12.9", features = ["json"] }
serde_json = "1.0.133"
thousands = "0.2.0"
lazy_static = "1.5.0"
rusqlite = "0.32.1"
dotenv = "0.15.0"
chrono = "0.4.38"

[build-dependencies]
cc = "1.2.6"
