#![cfg_attr(rustfmt, rustfmt_skip)]
// This file is autogenerated by build.rs, do not edit.

mod color_command;
mod dtag_command;
mod get_linked_account_command;
mod tag_command;
mod uptime_command;
pub mod tag_utils;
pub mod utils;

pub fn get_all_commands() -> Vec<poise::Command<crate::Data, crate::types::Error>> {
    vec![color_command::color(), dtag_command::dtag(), get_linked_account_command::get_linked_account(), tag_command::tag(), uptime_command::uptime()]
}