on:
  push:
    paths:
      - "**/*.rs"
      - "**/*.toml"
      - "**/*.lock"
      - "**/*.yml"

jobs:
  rustfmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Cargo fmt
        run: cargo +nightly fmt --all

  clippy:
    name: Lint Code
    needs: rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Clippy
        run: cargo +nightly clippy --workspace --all-targets --message-format=json -- -D warnings | tee clippy.json

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Cargo build
        run: cargo +nightly build --workspace --release

  audit:
    name: Audit
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Cargo audit
        run: cargo audit

  # tests:
  #   name: Tests
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4
  #     - name: Install nightly
  #       run: rustup install nightly
  #     - name: Cargo test
  #       run: cargo +nightly test --workspace --release
