on:
  push:
    paths:
      - '**/*.rs'
      - '**/*.toml'
      - '**/*.yml'

jobs:
  rustfmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install nightly
        run: rustup install nightly
      - name: Install Rustfmt
        run: rustup component add rustfmt --toolchain nightly
      - name: Cargo fmt
        run: cargo +nightly fmt --all

  clippy:
    name: Lint Code
    needs: rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install nightly
        run: rustup install nightly
      - name: Install Clippy
        run: rustup component add clippy --toolchain nightly
      - name: Run Clippy
        run: cargo +nightly clippy --workspace --all-targets --message-format=json -- -D warnings | tee clippy.json

  build:
    name: Build
    needs: [ rustfmt, clippy ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install nightly
        run: rustup install nightly
      - name: Cargo build
        run: cargo +nightly build --workspace --release

  tests:
    name: Tests
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install nightly
        run: rustup install nightly
      - name: Cargo test
        run: cargo +nightly test --workspace --release